services:
  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    container_name: kafka
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - tradepulse

  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tradepulse

  cust-service-db:
    image: postgres:latest
    container_name: cust-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - cust_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tradepulse

  order-service-db:
    image: postgres:latest
    container_name: order-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tradepulse

  payment-service-db:
    image: postgres:latest
    container_name: payment-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tradepulse

  stock-service-db:
    image: postgres:latest
    container_name: stock-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - stock_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tradepulse

  auth-service:
    build: ./auth-service
    image: auth-service:latest
    container_name: auth-service
    depends_on:
      auth-service-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - tradepulse

  payment-service:
    build: ./payment-service
    image: payment-service:latest
    container_name: payment-service
    depends_on:
      payment-service-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-service-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    networks:
      - tradepulse

  stock-service:
    build: ./stock-service
    image: stock-service:latest
    container_name: stock-service
    depends_on:
      stock-service-db:
        condition: service_healthy
    environment:
      POLYGON_API_KEY: ${POLYGON_API_KEY}
      POLYGON_FETCH_ENABLED: "true"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STOCK_KAFKA_TOPIC: stocks
      SPRING_DATASOURCE_URL: jdbc:postgresql://stock-service-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    networks:
      - tradepulse

  cust-service:
    build: ./cust-service
    image: cust-service:latest
    container_name: cust-service
    depends_on:
      cust-service-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      auth-service:
        condition: service_started
      stock-service:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cust-service-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - tradepulse

  order-service:
    build: ./order-service
    image: order-service-latest
    container_name: order-service
    depends_on:
      order-service-db:
        condition: service_healthy
      payment-service:
        condition: service_started
      cust-service:
        condition: service_started
      stock-service:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-service-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      ORDER_PAYMENT_SERVICE_ADDRESS: payment-service
      ORDER_PAYMENT_SERVICE_GRPC_PORT: 9002
      PORTFOLIO_SERVICE_GRPC_ADDRESS: cust-service
      PORTFOLIO_SERVICE_GRPC_PORT: 9004
      STOCK_SERVICE_GRPC_ADDRESS: stock-service
      STOCK_SERVICE_GRPC_PORT: 9003
    networks:
      - tradepulse

  analytics-service:
    build: ./analytics-service
    image: analytics-service:latest
    container_name: analytics-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - tradepulse

  api-gateway:
    build: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    depends_on:
      auth-service:
        condition: service_started
      cust-service:
        condition: service_started
      stock-service:
        condition: service_started
      order-service:
        condition: service_started
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    ports:
      - "4004:4004"
    networks:
      - tradepulse

networks:
  tradepulse:
    driver: bridge

volumes:
  auth_db_data:
  cust_db_data:
  order_db_data:
  payment_db_data:
  stock_db_data:
  kafka_data:
