spring.application.name=cust-service

logging.level.root=info
server.port=4000
spring.sql.init.mode=always
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

payment.service.address=${PAYMENT_SERVICE_ADDRESS:host.docker.internal}
payment.service.grpc.port=${PAYMENT_SERVICE_GRPC_PORT:9002}
auth.service.base-url=${AUTH_SERVICE_BASE_URL:http://auth-service:4005}
stock.service.base-url=${STOCK_SERVICE_BASE_URL:http://stock-service:4003}
