spring.application.name=order-service
server.port=4006
logging.level.root=info

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

order.payment.service.address=${ORDER_PAYMENT_SERVICE_ADDRESS:payment-service}
order.payment.service.grpc.port=${ORDER_PAYMENT_SERVICE_GRPC_PORT:9002}
stock.service.grpc.address=${STOCK_SERVICE_GRPC_ADDRESS:stock-service}
stock.service.grpc.port=${STOCK_SERVICE_GRPC_PORT:9003}
portfolio.sync.service.address=${PORTFOLIO_SYNC_SERVICE_ADDRESS:cust-service}
portfolio.sync.service.grpc.port=${PORTFOLIO_SYNC_SERVICE_GRPC_PORT:9004}
