spring.application.name=order-service
server.port=4006
logging.level.root=info

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/tradepulse_order}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

order.payment.service.address=${ORDER_PAYMENT_SERVICE_ADDRESS:host.docker.internal}
order.payment.service.grpc.port=${ORDER_PAYMENT_SERVICE_GRPC_PORT:9002}
portfolio.service.base-url=${PORTFOLIO_SERVICE_BASE_URL:http://cust-service:4000}
stock.service.base-url=${STOCK_SERVICE_BASE_URL:http://stock-service:4003}
