POST http://localhost:4004/api/customers
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe with kafka test5",
  "email": "kafka_test5@gmail.com",
  "phoneNumber": "6173456745",
  "address": "123 main street",
  "city": "Boston",
  "state": "MA",
  "country": "USA",
  "dateOfBirth": "1993-06-18",
  "registeredDate": "2026-02-04"
}